# Change this line to your root directory location
# ${Home}
HOME: /cluster/home/dzhu
ROOT_DIR: /cluster/home/dzhu/Documents/Projects/


DATA: /cluster/home/dzhu/DATA

# Original data variables (before pre-processing)
DATA_RAW:
  ROOT: ${DATA}/HNK_raw
  CLINICAL: 'clinical_info.csv'
  RADIOMIC: 'radiomic_features.csv'


DATA_CACHE: ${DATA}/.cache

# Pre-processed files location

DATA_PROCESSED:
  ROOT: /cluster/home/dzhu/Documents/DATA/UHN-Project/Radiomics_HN2/Preprocessed/OPC1
  CLINICAL_INFO: clinical_info.csv
  RADIOMIC: OPC1_radiomic_features_mad.csv
  VOLUME_CLINIC: VolumeAndClinic_OPC1_subsite.csv
  CLINIC: Clinic_OPC1.csv
  INPUT_TEST_TRAIN: train_test
  SPLIT: Split.csv
  TARGET: clinical_info.csv
  FEATURE: OPC1_radiomic_features_mad.csv
  IMAGE_PATH: /cluster/home/dzhu/Documents/DATA/UHN-Project/Radiomics_HN2/Preprocessed/OPC1/images

#DATA_PROCESSED:
#   ROOT: ${HOME}/Documents/DATA/UHN-Project/Radiomics_HN2/Preprocessed/OPC1
#   IMAGE_PATH: ${HOME}/Documents/DATA/UHN-Project/Radiomics_HN2/Preprocessed/OPC1/images
#   TARGET: clinical_info.csv
#   FEATURE: OPC1_radiomic_features_mad.csv
#   VOLUME_CLINIC: VolumeAndClinic_OPCs.csv
#   CLINIC: Clinic_OPC1.csv
#   INPUT_TEST_TRAIN: train_test
#   SPLIT: Split.csv

#DATA_PROCESSED:
#  ROOT: ${HOME}/Documents/DATA/UHN-Project/Genomic/Processed/GeneratedData/CTRPv2_GDSC/
#  CLINICAL_INFO: train_test_response_Erlotinib.csv
#  RADIOMIC: train_test_expression_Erlotinib.csv
#  VOLUME_CLINIC: train_test_expression_Erlotinib.csv
#  CLINIC: CTRPv2_Erlotinib.csv
#  INPUT_TEST_TRAIN: train_test_Erlotinib
#  SPLIT: Split.csv




# Set log level according to https://docs.python.org/3/library/logging.html#logging-levels
LOG:
  DIR: ${HOME}/Documents/DATA/UHN-Project/Genomic/Processed/GeneratedData/CTRPv2_GDSC/log
  LEVEL_CONSOLE: 20
  LEVEL_FILE: 10


# Rotations for X, Y and Z axes
# At least there should be a rotation for each axisIMAGE_ROTATIONS: [1,1,4]
ROTATION:
  x: 1
  y: 1
  z: 4

LOG_LEVEL_CONSOLE: 10
LOG_LEVEL_FILE: 10

DATA_BATCH_SIZE: 2

# Default path to save the results
SESSION_SAVE_PATH: ${HOME}/Documents/DATA/UHN-Project/Radiomics_HN2/Preprocessed/OPC1/Result

#SESSION_SAVE_PATH: ${HOME}/Documents/DATA/UHN-Project/Genomic/Processed/GeneratedData/CTRPv2_GDSC/Result/Erlotinib
# Default path to save the summaries
SUMMARIES_DIR: ${HOME}/Documents/DATA/UHN-Project/Genomic/Processed/GeneratedData/CTRPv2_GDSC/Summaries/Erlotinib
RANDOM_SEED:


CATEGORY: 5

#: The total number of features that are provided by the CSV of radiomic features
NUMBER_FEATURES: 724
VOLUME_FEATURE_INDEX: 26

COX:
  RESULT_PATH: ${Home}/Documents/DATA/UHN-Project/Radiomics_HN2/Preprocessed/OPC1/Cox

ML:
   RESULT_PATH: ${HOME}/Documents/DATA/UHN-Project/Genomic/Processed/GeneratedData/CTRPv2_GDSC/Result/ML/Erlotinib

#These parameter are used for hyper parameter selection in cpu and gpu hyper parameter selection
HYPER_PARAM:
  model:
  - ClinicalOnlySiamese
  - ClinicalOnlySiamese2
  - ClinicalOnlySiamese3
  - ClinicalVolumeSiamese
  - ClinicalVolumeSiamese2
  - ClinicalVolumeSiamese3
  cv_folds:
  - 5
  test_size: .25
  mrmr_size:
  - 0
  num_epochs:
  - 100
  batch_size:
  - 100
  regularization:
  - 0.5
  - 0.8
  learningRate:
  - 0.0003
  running_time: 5
  log_path: ${Home}/Documents/DATA/UHN-Project/Radiomics_HN2/Preprocessed/OPC1/HYPERPARAM

#These parameter are used for generating inputs in "train_test_generators.py"
GENERATOR:
  ROOT: ${HOME}/Documents/DATA/UHN-Project/Radiomics_HN2/Preprocessed/OPC1/
  MRMR: [50,20,100,200]
  CV_FOLDS: [1]
  TEST_SIZE: 0.2
  SPLIT_NUMBER: 10
  SPLITING_MODEL: [1]
  OUTPUT_PATH: 'Bo/'
  TARGET_PATH: 'clinical_info.csv'
  INPUT_FEATURES: 'OPC1_radiomic_features_mad.csv'
  SURVIVAL: True
