# Change this line to your root directory location
# ${Home}
DATA: /cluster/home/dzhu/Documents/DATA/UHN-Project/Radiomics_HN2/Preprocessed/OPC1

DATA_PROCESSED:
  CLINICAL_PATH: clinical_info.csv
  RADIOMICS_PATH: hn_radiomics_opc1.csv

PATH:
  IMAGE: images/

HPARAMS:
  EPOCHS: 10
  USE_IMAGES: False
  USE_RADIOMICS: False

  FCLAYERS: [1556, 16, 32, 64, 32, 32, 1]
  DROPOUT:   [0, 0.9, 0.9, 0.7, 0.7, 0]

  USE_DISTANCE: False
  DLAYERS: [16, 8, 1]


  TEST_RATIO: 0.3
  VAL_RATIO: 0.2
  BATCH_SIZE: 256
  NUM_WORKERS: 16

  ### K CROSS VALIDATION
  FOLDS: 5
  USE_FOLDS: False

  ### OPTIMIZER
  LR: 0.01
  MOMENTUM: 0.9
  WEIGHT_DECAY: 0
  SC_MILESTONES: [1, 2, 5, 15, 30]
  SC_GAMMA: 0.35

